import { Customer } from "@/types/customers";

export const sampleCustomers: Customer[] = [
  {
    id: "1",
    name: "Priscilla Diongoli",
    email: "priscilla.diongoli@domain.com",
    totalSpent: 1250.0,
    token: "USDC",
    payments: 12,
    frequency: "Monthly",
    lastPayment: "Nov 02, 2024",
  },
  {
    id: "2",
    name: "John Okafor",
    email: "john.okafor@myemail.com",
    totalSpent: 240.0,
    token: "USDT",
    payments: 12,
    frequency: "Monthly",
    lastPayment: "Oct 28, 2024",
  },
  {
    id: "3",
    name: "Timothy Ike",
    email: "timothy.ike@serviceprovider.com",
    totalSpent: 1728.0,
    token: "USDC",
    payments: 12,
    frequency: "Yearly",
    lastPayment: "Nov 01, 2024",
  },
  {
    id: "4",
    name: "Deborah Ovunda",
    email: "deborah.ovunda@inbox.com",
    totalSpent: 60.0,
    token: "USDT",
    payments: 3,
    frequency: "Monthly",
    lastPayment: "Aug 12, 2024",
  },
  {
    id: "5",
    name: "David Aliyus",
    email: "david.aliyus@contact.com",
    totalSpent: 320.0,
    token: "USDC",
    payments: 16,
    frequency: "Monthly",
    lastPayment: "Oct 30, 2024",
  },
  {
    id: "6",
    name: "Peter Pakabo",
    email: "peter.pakabo@samplemail.com",
    totalSpent: 3000.0,
    token: "USDC",
    payments: 2,
    frequency: "Yearly",
    lastPayment: "Nov 03, 2024",
  },
  {
    id: "7",
    name: "Simon Rabiu",
    email: "simon.rabiu@example.com",
    totalSpent: 96.0,
    token: "USDT",
    payments: 12,
    frequency: "Monthly",
    lastPayment: "Sep 15, 2024",
  },
  {
    id: "8",
    name: "Sarah Oyintare",
    email: "sarah.oyintare@provider.com",
    totalSpent: 480.0,
    token: "USDC",
    payments: 1,
    frequency: "Yearly",
    lastPayment: "Oct 29, 2024",
  },
  {
    id: "9",
    name: "Timothy Perebuowei",
    email: "timothy.perebuowei@service.com",
    totalSpent: 128.0,
    token: "USDT",
    payments: 8,
    frequency: "Monthly",
    lastPayment: "Oct 25, 2024",
  },
  {
    id: "10",
    name: "Deborah Wakili",
    email: "deborah.wakili@companymail.com",
    totalSpent: 24.0,
    token: "USDC",
    payments: 3,
    frequency: "Monthly",
    lastPayment: "Aug 30, 2024",
  },
  {
    id: "11",
    name: "Stephen Amachree",
    email: "stephen.amachree@business.com",
    totalSpent: 2500.0,
    token: "USDT",
    payments: 2,
    frequency: "Yearly",
    lastPayment: "Nov 03, 2024",
  },
  {
    id: "12",
    name: "Joseph Kolapo",
    email: "joseph.kolapo@webmail.com",
    totalSpent: 300.0,
    token: "USDC",
    payments: 15,
    frequency: "Monthly",
    lastPayment: "Oct 31, 2024",
  },
  {
    id: "13",
    name: "Joseph Ibe",
    email: "joseph.ibe@mydomain.com",
    totalSpent: 280.0,
    token: "USDT",
    payments: 14,
    frequency: "Monthly",
    lastPayment: "Nov 01, 2024",
  },
  {
    id: "14",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    totalSpent: 540.0,
    token: "USDC",
    payments: 1,
    frequency: "Yearly",
    lastPayment: "Oct 27, 2024",
  },
  {
    id: "15",
    name: "Ahmed Hassan",
    email: "ahmed.hassan@mail.com",
    totalSpent: 720.0,
    token: "USDT",
    payments: 1,
    frequency: "Yearly",
    lastPayment: "Nov 02, 2024",
  },
  {
    id: "16",
    name: "Lisa Chen",
    email: "lisa.chen@email.com",
    totalSpent: 8.0,
    token: "USDC",
    payments: 1,
    frequency: "One-off",
    lastPayment: "Oct 15, 2024",
  },
  {
    id: "17",
    name: "Michael Brown",
    email: "michael.brown@mail.com",
    totalSpent: 16.0,
    token: "USDT",
    payments: 2,
    frequency: "One-off",
    lastPayment: "Sep 22, 2024",
  },
];
