import { Transaction } from "@/types/transactions";

export const sampleTransactions: Transaction[] = [
  {
    id: "1",
    email: "priscilla.diongoli@domain.com",
    amount: 250.0,
    token: "USDC",
    status: "Pending",
    frequency: "One-off",
    paidVia: "Strimz",
    timestamp: "Aug 14, 24 | 10:15",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "2",
    email: "john.okafor@myemail.com",
    amount: 20.0,
    token: "USDC",
    status: "Successful",
    frequency: "Monthly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 12:30",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "3",
    email: "timothy.ike@serviceprovider.com",
    amount: 144.0,
    token: "USDC",
    status: "Successful",
    frequency: "Yearly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 10:45",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "4",
    email: "deborah.ovunda@inbox.com",
    amount: 20.0,
    token: "USDC",
    status: "Failed",
    frequency: "Monthly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 10:00",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "5",
    email: "david.aliyus@contact.com",
    amount: 8.0,
    token: "USDC",
    status: "Successful",
    frequency: "One-off",
    paidVia: "Strimz",
    timestamp: "Aug 14, 24 | 10:30",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "6",
    email: "peter.pakabo@samplemail.com",
    amount: 250.0,
    token: "USDC",
    status: "Successful",
    frequency: "Yearly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 12:15",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "7",
    email: "simon.rabiu@example.com",
    amount: 8.0,
    token: "USDC",
    status: "Successful",
    frequency: "One-off",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 11:30",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "8",
    email: "sarah.oyintare@provider.com",
    amount: 8.0,
    token: "USDC",
    status: "Failed",
    frequency: "One-off",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 11:15",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "9",
    email: "timothy.perebuowei@service.com",
    amount: 8.0,
    token: "USDC",
    status: "Successful",
    frequency: "One-off",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 12:00",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "10",
    email: "deborah.wakili@companymail.com",
    amount: 8.0,
    token: "USDC",
    status: "Failed",
    frequency: "One-off",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 13:00",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "11",
    email: "stephen.amachree@business.com",
    amount: 250.0,
    token: "USDC",
    status: "Successful",
    frequency: "Yearly",
    paidVia: "Strimz",
    timestamp: "Aug 14, 24 | 11:45",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "12",
    email: "joseph.kolapo@webmail.com",
    amount: 20.0,
    token: "USDC",
    status: "Successful",
    frequency: "Monthly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 12:45",
    txnHash: "0x211d57bfd21...",
  },
  {
    id: "13",
    email: "joseph.ibe@mydomain.com",
    amount: 20.0,
    token: "USDC",
    status: "Successful",
    frequency: "Monthly",
    paidVia: "Transfer",
    timestamp: "Aug 14, 24 | 11:00",
    txnHash: "0x211d57bfd21...",
  },
];
